baseURL = "https://example.org/"
languageCode = "en-us"
title = "My New Hugo Project"
theme = "PaperMod"
[pagination]
  pagerSize = 10
[params]
  ShowReadingTime = true
  ShowShareButtons = true
  defaultTheme = "auto"